"""fix typo

Revision ID: 3283b2c1e9aa
Revises: 0001_init
Create Date: 2025-09-29 20:26:15.796138

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3283b2c1e9aa'
down_revision = '0001_init'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sessions_employee_id', table_name='sessions')
    op.drop_index('ix_sessions_id', table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('photo', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('photo_uploaded_at', sa.DATETIME(), nullable=True),
    sa.Column('sent_to_ml_at', sa.DATETIME(), nullable=True),
    sa.Column('processed_at', sa.DATETIME(), nullable=True),
    sa.Column('actual_tools', sqlite.JSON(), nullable=True),
    sa.Column('detected_tools', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_id', 'sessions', ['id'], unique=False)
    op.create_index('ix_sessions_employee_id', 'sessions', ['employee_id'], unique=False)
    # ### end Alembic commands ###

"""fix typo

Revision ID: 3283b2c1e9aa
Revises: 0001_init
Create Date: 2025-09-29 20:26:15.796138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '3283b2c1e9aa'
down_revision: Union[str, None] = '0001_init'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sessions_employee_id', table_name='sessions')
    op.drop_index('ix_sessions_id', table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('photo', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('photo_uploaded_at', sa.DATETIME(), nullable=True),
    sa.Column('sent_to_ml_at', sa.DATETIME(), nullable=True),
    sa.Column('processed_at', sa.DATETIME(), nullable=True),
    sa.Column('actual_tools', sqlite.JSON(), nullable=True),
    sa.Column('detected_tools', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_id', 'sessions', ['id'], unique=False)
    op.create_index('ix_sessions_employee_id', 'sessions', ['employee_id'], unique=False)
    # ### end Alembic commands ###
