"""Remove null for status timestamps

Revision ID: 982a534d6a1b
Revises: 3283b2c1e9aa
Create Date: 2025-09-29 23:13:01.778597

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '982a534d6a1b'
down_revision = '3283b2c1e9aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

"""Remove null for status timestamps

Revision ID: 982a534d6a1b
Revises: 3283b2c1e9aa
Create Date: 2025-09-29 23:13:01.778597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '982a534d6a1b'
down_revision: Union[str, None] = '3283b2c1e9aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
